#!/usr/bin/env python3
import sys, json, datetime, re

header = '''# This file was autogenerated at {0}.
# Do not change it, see source json bsp file and 'tools/json2py.py'
import bsp
import consts

__bsp = {1}
__cfg = None

def get_config():
    global __cfg
    if __cfg is None:
        __cfg = bsp.gen_bsp(__bsp)
    return __cfg

def __getattr__(name):
    cfg = get_config()
    if name in cfg:
        return cfg[name]
    raise AttributeError()

'''

class JSONWithCommentsDecoder(json.JSONDecoder):
    def __init__(self, **kw):
        super().__init__(**kw)

    def decode(self, s: str):
        s = '\n'.join(l for l in s.split('\n') if not l.lstrip(' ').startswith('//'))
        return super().decode(s)

def _resolve_consts(json_str: str) -> str:
    '''Replace "@consts.NAME" JSON strings with live "consts.NAME" Python expressions'''
    return re.sub(r'"@consts\.([A-Z_][A-Z0-9_]*)"', r'consts.\1', json_str)


if __name__ == '__main__':
    bsp_py = json.dumps(json.loads(sys.stdin.read(), cls=JSONWithCommentsDecoder))
    bsp_py = _resolve_consts(bsp_py)
    print( header.format(datetime.datetime.now(), bsp_py))
