# This file was autogenerated at 2023-11-02 12:47:01.075179.
# Do not change it, see source json bsp file and 'tools/json2py.py'
import bsp

__bsp = {'network': {'import': 'hw.esp32.wlan', 'type': 'WLAN'}}
__cfg = None

def get_config():
    global __cfg
    if __cfg is None:
        __cfg = bsp.gen_bsp(__bsp)
    return __cfg

def __getattr__(name):
    cfg = get_config()
    if name in cfg:
        return cfg[name]
    raise AttributeError()


