# This file was autogenerated at 2023-10-27 18:52:53.362497.
# Do not change it, see source json bsp file and 'tools/json2py.py'
import bsp

__bsp = {'ble': {'import': 'hw.linux.ble', 'type': 'BLEUART'}, 'network': {'import': 'hw.linux.wlan', 'type': 'WLAN'}}
__cfg = None

def get_config():
    global __cfg
    if __cfg is None:
        __cfg = bsp.gen_bsp(__bsp)
    return __cfg

def __getattr__(name):
    cfg = get_config()
    if name in cfg:
        return cfg[name]
    raise AttributeError()


