# This file was autogenerated at 2023-06-19 12:50:18.472211.
# Do not change it, see source json bsp file and 'tools/json2py.py'
import bsp

__bsp = {'gpio': {'address': '0x38', 'i2c': '&i2c', 'import': 'pcf8574', 'type': 'PCF8574'}, 'i2c': {'freq': 400000, 'id': 0, 'import': 'machine', 'scl': {'id': 18, 'import': 'machine', 'type': 'Pin'}, 'sda': {'id': 19, 'import': 'machine', 'type': 'Pin'}, 'type': 'I2C'}}
__cfg = None

def get_config():
    global __cfg
    if __cfg is None:
        __cfg = bsp.gen_bsp(__bsp)
    return __cfg

def __getattr__(name):
    cfg = get_config()
    if name in cfg:
        return cfg[name]
    raise AttributeError()


