name: Release CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CppCheck:
    name: 'Статическое тестирование кода'
    runs-on: buildkitsandbox
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: ./ci/00-code-check.sh
    - uses: actions/upload-artifact@v2
      with:
        name: 'cppcheck'
        path: out/code-check.log
  Build:
    name: 'Сборка'
    runs-on: buildkitsandbox
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: ./ci/00-build.sh
    - uses: actions/upload-artifact@v2
      with:
        name: 'fw.fs'
        path: out/fw.fs
    - uses: actions/upload-artifact@v2
      with:
        name: 'AR.FW.latest.uebf'
        path: out/AR.FW.latest.uebf
  Test:
    name: 'Тестирование'
    runs-on: buildkitsandbox
    needs: Build
    steps:
    - run: ./ci/01-tests-simu.sh
    - uses: actions/upload-artifact@v2
      with:
        name: 'tests-summary'
        path: out/tests/
  Release:
    name: 'Подготовка релиза'
    runs-on: buildkitsandbox
    needs: Test
    # if: github.event_name == 'push' && (contains(github.ref, '/heads/master') || contains(github.ref, '/tags/v')))
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
          submodules: recursive
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - run: ./ci/02-release-prepare.sh
